version: '3.1'
services:
  mongo-db:
    image: mongo:latest
    ports:
      - '27017:27017'
  app-backend:
    container_name: photo-grid-backend
    restart: always
    build: .
    ports:
      - '3333:3333'
    links:
      - mongo-db
