version: '3.1'
services:
  app:
    container_name: photo-grid-api
    restart: always
    build: .
    ports:
      - '3333:3333'
    links:
      - mongo-db
  mongo-db:
    image: mongo:latest
    ports:
      - '27017:27017'
